# Конфигурационный файл Docker Compose для базы данных приложения фитнес-клуба.
#
# Описание:
# Этот файл определяет сервис базы данных PostgreSQL, который используется
# серверной частью приложения фитнес-клуба.
#
# Автор: Милана
# Версия: 1.0
# Дата: 2025-04-29

# Версия формата Docker Compose
version: '3.5'
# Определение сервисов
services:
  # Сервис базы данных PostgreSQL
  db_auth:
    # Образ Docker: PostgreSQL на основе Alpine Linux
    image: postgres:alpine
    # Имя контейнера
    container_name: fitness_db
    # Прокидывание портов: 5432 (хост) -> 5432 (контейнер)
    ports:
      - "5432:5432"
      # Переменные окружения для настройки PostgreSQL
    environment:
      # Имя пользователя базы данных
      - POSTGRES_USER=postgres
      # Пароль для пользователя базы данных
      - POSTGRES_PASSWORD=root